import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" navbar bg-slate-300 p-5">
          <Link className="mx-5" href={'/'}>home</Link>
          <Link href={'/coils'}>coils</Link>
          <Link className="mx-5" href={'/move'}>Move coils</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
